import { Link } from 'react-router-dom'
import { useQuery } from 'convex/react'
import { api } from '../../convex/_generated/api'
import { formatEventDate, formatPrice, getSaleStatusBadge } from '../utils/eventFormatters'

export function AdminEvents() {
  // Note: api.events will be available once convex dev is run
  // @ts-expect-error - events module will be generated by convex
  const eventsData = useQuery(
    api.events?.getEvents || 'skip',
    { page: 0, pageSize: 50 }
  )

  // @ts-expect-error - events module will be generated by convex
  const myTickets = useQuery(api.events?.getUserTickets || 'skip', { upcomingOnly: false })

  const events = eventsData?.items || []
  const loading = !eventsData

  // Calculate revenue from tickets sold
  const calculateRevenue = (eventId: string) => {
    if (!myTickets) return 0
    
    const eventTickets = myTickets.filter((t: { event: { _id: string } }) => t.event._id === eventId)
    // This is a simplified calculation - in a real app, you'd query actual sales data
    return eventTickets.reduce((sum: number, ticket: { quantity: number; ticketType: string }) => {
      // Estimate price based on ticket type (this should come from actual purchase data)
      const estimatedPrice = ticket.ticketType === 'vip' ? 150 : ticket.ticketType === 'early_bird' ? 30 : 50
      return sum + (ticket.quantity * estimatedPrice)
    }, 0)
  }

  if (loading) {
    return (
      <div className="admin-events-page">
        <div className="loading-container">
          <div className="spinner-large"></div>
          <p className="loading-text">Loading events...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="admin-events-page">
      <div className="page-container">
        {/* Header */}
        <div className="page-header">
          <div className="header-content">
            <h1 className="page-title">Manage Events</h1>
            <p className="page-subtitle">Create and manage your events</p>
          </div>
          <Link to="/admin/events/new" className="create-button">
            <iconify-icon icon="solar:add-circle-bold"></iconify-icon>
            <span>Create Event</span>
          </Link>
        </div>

        {/* Stats Overview */}
        <div className="stats-grid">
          <div className="stat-card">
            <div className="stat-icon" style={{ background: 'rgba(6, 182, 212, 0.2)' }}>
              <iconify-icon icon="solar:calendar-bold" style={{ color: 'var(--color-primary)' }}></iconify-icon>
            </div>
            <div className="stat-content">
              <div className="stat-value">{events.length}</div>
              <div className="stat-label">Total Events</div>
            </div>
          </div>

          <div className="stat-card">
            <div className="stat-icon" style={{ background: 'rgba(34, 197, 94, 0.2)' }}>
              <iconify-icon icon="solar:ticket-bold" style={{ color: '#22c55e' }}></iconify-icon>
            </div>
            <div className="stat-content">
              <div className="stat-value">
                {events.reduce((sum: number, e: { ticketsSold: number }) => sum + e.ticketsSold, 0)}
              </div>
              <div className="stat-label">Tickets Sold</div>
            </div>
          </div>

          <div className="stat-card">
            <div className="stat-icon" style={{ background: 'rgba(168, 85, 247, 0.2)' }}>
              <iconify-icon icon="solar:dollar-minimalistic-bold" style={{ color: '#a855f7' }}></iconify-icon>
            </div>
            <div className="stat-content">
              <div className="stat-value">
                {formatPrice(events.reduce((sum: number, e: { _id: string }) => sum + calculateRevenue(e._id), 0))}
              </div>
              <div className="stat-label">Total Revenue</div>
            </div>
          </div>
        </div>

        {/* Events List */}
        {events.length === 0 ? (
          <div className="empty-state">
            <iconify-icon icon="solar:calendar-minimalistic-bold" class="empty-icon"></iconify-icon>
            <h2 className="empty-title">No Events Yet</h2>
            <p className="empty-description">
              Create your first event to get started
            </p>
            <Link to="/admin/events/new" className="empty-action">
              <iconify-icon icon="solar:add-circle-bold"></iconify-icon>
              <span>Create Event</span>
            </Link>
          </div>
        ) : (
          <div className="events-list">
            {events.map((event: {
              _id: string
              title: string
              imageUrl: string
              startAtUtc: number
              city: string
              saleStatus: 'upcoming' | 'on_sale' | 'sold_out' | 'cancelled'
              capacity: number
              ticketsSold: number
              creator: {
                displayName: string
              }
            }) => {
              const statusBadge = getSaleStatusBadge(event.saleStatus)
              const revenue = calculateRevenue(event._id)
              const soldPercentage = (event.ticketsSold / event.capacity) * 100

              return (
                <div key={event._id} className="event-card">
                  <div className="event-image-container">
                    <img src={event.imageUrl} alt={event.title} className="event-image" />
                    <div className={`status-badge ${statusBadge.bgColor} ${statusBadge.color}`}>
                      {statusBadge.text}
                    </div>
                  </div>

                  <div className="event-content">
                    <div className="event-main">
                      <h3 className="event-title">{event.title}</h3>
                      
                      <div className="event-meta">
                        <div className="meta-item">
                          <iconify-icon icon="solar:calendar-bold"></iconify-icon>
                          <span>{formatEventDate(event.startAtUtc, 'America/New_York')}</span>
                        </div>
                        <div className="meta-item">
                          <iconify-icon icon="solar:map-point-bold"></iconify-icon>
                          <span>{event.city}</span>
                        </div>
                      </div>

                      <div className="event-stats">
                        <div className="stat-item">
                          <span className="stat-label">Tickets Sold</span>
                          <div className="stat-value-inline">
                            {event.ticketsSold} / {event.capacity}
                            <span className="stat-percentage">({soldPercentage.toFixed(0)}%)</span>
                          </div>
                          <div className="progress-bar">
                            <div 
                              className="progress-fill" 
                              style={{ width: `${Math.min(soldPercentage, 100)}%` }}
                            ></div>
                          </div>
                        </div>

                        <div className="stat-item">
                          <span className="stat-label">Revenue</span>
                          <div className="stat-value-inline revenue">
                            {formatPrice(revenue)}
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="event-actions">
                      <Link 
                        to={`/events/${event._id}`} 
                        className="action-button view-button"
                      >
                        <iconify-icon icon="solar:eye-bold"></iconify-icon>
                        <span>View</span>
                      </Link>
                      <button className="action-button edit-button" disabled>
                        <iconify-icon icon="solar:pen-bold"></iconify-icon>
                        <span>Edit</span>
                      </button>
                      <button className="action-button delete-button" disabled>
                        <iconify-icon icon="solar:trash-bin-trash-bold"></iconify-icon>
                      </button>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>

      <style>{`
        .admin-events-page {
          max-width: 1400px;
          margin: 0 auto;
          padding: 40px 20px;
        }

        .page-container {
          display: flex;
          flex-direction: column;
          gap: 32px;
        }

        .loading-container {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          min-height: 60vh;
          gap: 16px;
        }

        .spinner-large {
          width: 48px;
          height: 48px;
          border: 4px solid rgba(6, 182, 212, 0.2);
          border-top-color: var(--color-primary);
          border-radius: 50%;
          animation: spin 0.8s linear infinite;
        }

        .loading-text {
          font-size: 14px;
          color: var(--color-text-dim);
        }

        @keyframes spin {
          to { transform: rotate(360deg); }
        }

        .page-header {
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          gap: 24px;
        }

        .header-content {
          flex: 1;
        }

        .page-title {
          font-size: 32px;
          font-weight: 800;
          color: white;
          margin: 0 0 8px 0;
        }

        .page-subtitle {
          font-size: 14px;
          color: var(--color-text-dim);
          margin: 0;
        }

        .create-button {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 12px 24px;
          background: var(--color-primary);
          border: none;
          border-radius: 8px;
          color: white;
          font-size: 14px;
          font-weight: 700;
          text-decoration: none;
          cursor: pointer;
          transition: all 0.2s;
          white-space: nowrap;
        }

        .create-button:hover {
          background: #0891b2;
          transform: translateY(-2px);
        }

        .create-button iconify-icon {
          font-size: 20px;
        }

        .stats-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
        }

        .stat-card {
          display: flex;
          align-items: center;
          gap: 16px;
          padding: 24px;
          background: var(--color-card-bg);
          border: 1px solid var(--color-card-border);
          border-radius: 12px;
          transition: all 0.2s;
        }

        .stat-card:hover {
          border-color: var(--color-primary);
          transform: translateY(-2px);
        }

        .stat-icon {
          width: 56px;
          height: 56px;
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 28px;
          flex-shrink: 0;
        }

        .stat-content {
          flex: 1;
        }

        .stat-value {
          font-size: 28px;
          font-weight: 800;
          color: white;
          line-height: 1;
          margin-bottom: 4px;
        }

        .stat-label {
          font-size: 13px;
          color: var(--color-text-dim);
          font-weight: 500;
        }

        .empty-state {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 80px 20px;
          text-align: center;
        }

        .empty-icon {
          font-size: 64px;
          color: var(--color-text-dim);
          opacity: 0.5;
          margin-bottom: 16px;
        }

        .empty-title {
          font-size: 24px;
          font-weight: 700;
          color: white;
          margin: 0 0 8px 0;
        }

        .empty-description {
          font-size: 14px;
          color: var(--color-text-dim);
          margin: 0 0 24px 0;
        }

        .empty-action {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 12px 24px;
          background: var(--color-primary);
          border-radius: 8px;
          color: white;
          font-size: 14px;
          font-weight: 700;
          text-decoration: none;
          transition: all 0.2s;
        }

        .empty-action:hover {
          background: #0891b2;
          transform: translateY(-2px);
        }

        .events-list {
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .event-card {
          display: flex;
          gap: 20px;
          padding: 20px;
          background: var(--color-card-bg);
          border: 1px solid var(--color-card-border);
          border-radius: 12px;
          transition: all 0.2s;
        }

        .event-card:hover {
          border-color: var(--color-primary);
        }

        .event-image-container {
          position: relative;
          width: 200px;
          height: 140px;
          flex-shrink: 0;
          border-radius: 8px;
          overflow: hidden;
        }

        .event-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .status-badge {
          position: absolute;
          top: 8px;
          right: 8px;
          padding: 4px 12px;
          border-radius: 12px;
          font-size: 11px;
          font-weight: 700;
          text-transform: uppercase;
        }

        .event-content {
          flex: 1;
          display: flex;
          gap: 20px;
          justify-content: space-between;
        }

        .event-main {
          flex: 1;
        }

        .event-title {
          font-size: 18px;
          font-weight: 700;
          color: white;
          margin: 0 0 12px 0;
          line-height: 1.3;
        }

        .event-meta {
          display: flex;
          gap: 16px;
          margin-bottom: 16px;
        }

        .meta-item {
          display: flex;
          align-items: center;
          gap: 6px;
          font-size: 13px;
          color: var(--color-text-dim);
        }

        .meta-item iconify-icon {
          font-size: 16px;
          color: var(--color-primary);
        }

        .event-stats {
          display: flex;
          gap: 24px;
        }

        .stat-item {
          flex: 1;
        }

        .stat-label {
          display: block;
          font-size: 11px;
          color: var(--color-text-dim);
          margin-bottom: 4px;
          text-transform: uppercase;
          font-weight: 600;
        }

        .stat-value-inline {
          font-size: 16px;
          font-weight: 700;
          color: white;
        }

        .stat-value-inline.revenue {
          color: var(--color-primary);
        }

        .stat-percentage {
          font-size: 13px;
          color: var(--color-text-dim);
          margin-left: 4px;
        }

        .progress-bar {
          margin-top: 6px;
          height: 6px;
          background: rgba(255, 255, 255, 0.1);
          border-radius: 3px;
          overflow: hidden;
        }

        .progress-fill {
          height: 100%;
          background: var(--color-primary);
          transition: width 0.3s ease;
        }

        .event-actions {
          display: flex;
          flex-direction: column;
          gap: 8px;
          justify-content: center;
        }

        .action-button {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 8px 16px;
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--color-card-border);
          border-radius: 6px;
          color: white;
          font-size: 13px;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s;
          text-decoration: none;
          white-space: nowrap;
        }

        .action-button:hover:not(:disabled) {
          background: rgba(255, 255, 255, 0.08);
          transform: translateX(-2px);
        }

        .action-button:disabled {
          opacity: 0.4;
          cursor: not-allowed;
        }

        .action-button iconify-icon {
          font-size: 16px;
        }

        .view-button:hover:not(:disabled) {
          border-color: var(--color-primary);
          color: var(--color-primary);
        }

        .edit-button:hover:not(:disabled) {
          border-color: #a855f7;
          color: #a855f7;
        }

        .delete-button {
          padding: 8px 12px;
        }

        .delete-button:hover:not(:disabled) {
          border-color: rgb(239, 68, 68);
          color: rgb(239, 68, 68);
        }

        @media (max-width: 1024px) {
          .stats-grid {
            grid-template-columns: 1fr;
          }

          .event-card {
            flex-direction: column;
          }

          .event-image-container {
            width: 100%;
            height: 200px;
          }

          .event-content {
            flex-direction: column;
          }

          .event-actions {
            flex-direction: row;
          }

          .action-button {
            flex: 1;
            justify-content: center;
          }
        }

        @media (max-width: 640px) {
          .admin-events-page {
            padding: 20px 10px;
          }

          .page-header {
            flex-direction: column;
            align-items: stretch;
          }

          .create-button {
            justify-content: center;
          }

          .page-title {
            font-size: 24px;
          }

          .event-stats {
            flex-direction: column;
            gap: 16px;
          }

          .event-actions {
            gap: 8px;
          }
        }
      `}</style>
    </div>
  )
}
