import { useState, useCallback } from 'react'
import { useParams, Link, useNavigate } from 'react-router-dom'
import { useQuery } from 'convex/react'
import { api } from '../../convex/_generated/api'
import { Id } from '../../convex/_generated/dataModel'
import { QueueSection, CheckoutModal } from '../components/events'
import { CalendarExportModal } from '../components/CalendarExportModal'
import {
  formatEventTime,
  formatPrice,
  getSaleStatusBadge,
  getAvailabilityText,
  isEventPast,
} from '../utils/eventFormatters'

export function EventDetail() {
  const { eventId } = useParams<{ eventId: string }>()
  const navigate = useNavigate()
  const [isCheckoutOpen, setIsCheckoutOpen] = useState(false)
  const [isCalendarExportOpen, setIsCalendarExportOpen] = useState(false)

  const handleAdmitted = useCallback(() => {
    setIsCheckoutOpen(true)
  }, [])

  // Note: api.events will be available once convex dev is run
  const eventDetail = useQuery(
    api.events?.getEventDetail || 'skip',
    eventId ? { eventId: eventId as Id<'events'> } : 'skip'
  )

  // @ts-expect-error - events module will be generated by convex
  const relatedEvents = useQuery(
    api.events?.getEvents || 'skip',
    eventDetail?.event.city
      ? {
          page: 0,
          pageSize: 4,
          city: eventDetail.event.city,
          saleStatus: 'on_sale' as const,
        }
      : 'skip'
  )

  if (!eventDetail) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin h-12 w-12 border-4 border-red-600 border-t-transparent rounded-full"></div>
      </div>
    )
  }

  const { event, creator, ticketTypes, userContext } = eventDetail
  const statusBadge = getSaleStatusBadge(event.saleStatus)
  const isPast = isEventPast(event.endAtUtc)
  const hasTickets = ticketTypes.length > 0

  const handleCheckoutSuccess = (orderId: string) => {
    setIsCheckoutOpen(false)
    navigate(`/events/confirmation?orderId=${orderId}`)
  }

  const handleRequeue = () => {
    setIsCheckoutOpen(false)
    // QueueSection will handle re-joining if we clear any local state if needed
  }

  return (
    <div className="event-detail-layout app-surface-page app-surface-shell">
      {/* Navigation & Status Header */}
      <div className="detail-header-bar">
        <button 
          onClick={() => navigate('/events')}
          className="back-btn-compact"
        >
          <iconify-icon icon="solar:arrow-left-bold"></iconify-icon>
          <span>Events</span>
        </button>
        <div className="header-event-info">
          <h1 className="header-title">{event.title}</h1>
          <div className={`${statusBadge.bgColor} ${statusBadge.color} status-tag`}>
            {statusBadge.text}
          </div>
        </div>
        {!isPast && (
          <button
            onClick={() => setIsCalendarExportOpen(true)}
            className="header-action-btn"
          >
            <iconify-icon icon="solar:calendar-add-bold"></iconify-icon>
          </button>
        )}
      </div>

      <div className="compact-dashboard-grid">
        {/* Top Feature: Image & Meta */}
        <div className="feature-section">
          <div className="feature-image-wrapper">
            <img src={event.imageUrl} alt={event.title} className="feature-image" />
            <div className="feature-overlay">
              <div className="feature-meta-grid">
                <div className="feature-meta-item">
                  <iconify-icon icon="solar:calendar-bold"></iconify-icon>
                  <span>{formatEventTime(event.startAtUtc, event.timezone)}</span>
                </div>
                <div className="feature-meta-item">
                  <iconify-icon icon="solar:map-point-bold"></iconify-icon>
                  <span>{event.city}</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Content Row */}
        <div className="details-row">
          {/* About & Venue */}
          <div className="details-col-main">
            <section className="compact-section bio-section">
              <h2 className="compact-section-title">About Event</h2>
              <p className="compact-section-text">{event.description}</p>
            </section>
            
            <div className="venue-host-split">
              <section className="compact-section">
                <h2 className="compact-section-title">Venue</h2>
                <div className="compact-venue-info">
                  <p className="text-white font-bold text-sm">{event.address}</p>
                  <p className="text-gray-400 text-xs">{event.city}</p>
                </div>
              </section>

              <section className="compact-section">
                <h2 className="compact-section-title">Hosted By</h2>
                <Link to={`/profile/${creator._id}`} className="compact-creator-link">
                  <img src={creator.avatar} alt={creator.displayName} className="creator-mini-avatar" />
                  <span className="creator-mini-name">{creator.displayName}</span>
                </Link>
              </section>
            </div>
          </div>

          {/* Tickets & Actions */}
          <div className="details-col-tickets">
            <div className="tickets-status-card">
              <div className="availability-summary">
                <iconify-icon icon="solar:users-group-two-rounded-bold"></iconify-icon>
                <span>{getAvailabilityText(event.capacity, event.ticketsSold)}</span>
              </div>
              
              {isPast ? (
                <div className="past-event-msg">Event has ended</div>
              ) : event.saleStatus === 'on_sale' ? (
                <QueueSection 
                  eventId={event._id} 
                  onAdmitted={handleAdmitted} 
                />
              ) : (
                <div className="status-placeholder-msg">
                  {event.saleStatus === 'upcoming' ? 'Coming Soon' : 'Sold Out'}
                </div>
              )}
            </div>

            {hasTickets && (
              <div className="mini-ticket-scroller">
                {ticketTypes.map((ticket: typeof ticketTypes[number]) => (
                  <div key={ticket._id} className="mini-ticket-card">
                    <div className="mini-ticket-info">
                      <span className="mini-ticket-type">{ticket.type.replace('_', ' ').toUpperCase()}</span>
                      <span className="mini-ticket-price">{formatPrice(ticket.price)}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Modals */}
      {userContext?.checkoutSession && (
        <CheckoutModal
          isOpen={isCheckoutOpen}
          onClose={() => setIsCheckoutOpen(false)}
          eventId={event._id}
          eventTitle={event.title}
          ticketTypes={ticketTypes}
          checkoutSessionId={userContext.checkoutSession._id}
          onSuccess={handleCheckoutSuccess}
          onRequeue={handleRequeue}
        />
      )}

      <CalendarExportModal
        isOpen={isCalendarExportOpen}
        onClose={() => setIsCalendarExportOpen(false)}
        event={event}
      />

      <style>{`
        .event-detail-layout {
          max-width: 1400px;
          margin: 0 auto;
          padding: 0 40px 20px;
          height: 100%;
          display: flex;
          flex-direction: column;
          overflow: hidden;
        }

        /* Header Bar */
        .detail-header-bar {
          display: flex;
          align-items: center;
          gap: 20px;
          padding: 16px 0;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
          margin-bottom: 20px;
        }

        .back-btn-compact {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 8px 14px;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--color-card-border);
          border-radius: 8px;
          color: white;
          font-size: 13px;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s;
        }

        .back-btn-compact:hover {
          background: rgba(255, 255, 255, 0.08);
          border-color: var(--color-primary);
        }

        .header-event-info {
          flex: 1;
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .header-title {
          font-size: 20px;
          font-weight: 800;
          color: white;
          margin: 0;
        }

        .status-tag {
          font-size: 11px;
          font-weight: 700;
          padding: 2px 10px;
          border-radius: 20px;
          text-transform: uppercase;
        }

        .header-action-btn {
          background: none;
          border: 1px solid var(--color-card-border);
          border-radius: 8px;
          width: 38px;
          height: 38px;
          display: flex;
          align-items: center;
          justify-content: center;
          color: var(--color-primary);
          cursor: pointer;
          transition: all 0.2s;
        }

        .header-action-btn:hover {
          background: rgba(220, 38, 38, 0.1);
          border-color: var(--color-primary);
        }

        /* Dashboard Grid */
        .compact-dashboard-grid {
          flex: 1;
          display: flex;
          flex-direction: column;
          gap: 24px;
          min-height: 0;
        }

        .feature-section {
          height: 250px;
          border-radius: 16px;
          overflow: hidden;
          position: relative;
        }

        .feature-image-wrapper {
          width: 100%;
          height: 100%;
          position: relative;
        }

        .feature-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .feature-overlay {
          position: absolute;
          inset: 0;
          background: linear-gradient(to top, rgba(0,0,0,0.8) 0%, transparent 60%);
          display: flex;
          align-items: flex-end;
          padding: 24px;
        }

        .feature-meta-grid {
          display: flex;
          gap: 24px;
        }

        .feature-meta-item {
          display: flex;
          align-items: center;
          gap: 8px;
          color: white;
          font-size: 13px;
          background: rgba(0,0,0,0.5);
          padding: 6px 12px;
          border-radius: 8px;
          backdrop-filter: blur(4px);
          border: 1px solid rgba(255,255,255,0.1);
        }

        .feature-meta-item iconify-icon {
          color: var(--color-primary);
        }

        /* Details Row */
        .details-row {
          display: grid;
          grid-template-columns: 1fr 340px;
          gap: 24px;
          flex: 1;
          min-height: 0;
        }

        .details-col-main {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .compact-section {
          background: rgba(255,255,255,0.02);
          border: 1px solid var(--color-card-border);
          border-radius: 12px;
          padding: 16px;
        }

        .compact-section-title {
          font-size: 14px;
          font-weight: 700;
          color: rgba(255,255,255,0.5);
          text-transform: uppercase;
          letter-spacing: 0.05em;
          margin-bottom: 12px;
        }

        .compact-section-text {
          color: white;
          font-size: 14px;
          line-height: 1.5;
          margin: 0;
        }

        .venue-host-split {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 20px;
        }

        .compact-creator-link {
          display: flex;
          align-items: center;
          gap: 10px;
          text-decoration: none;
        }

        .creator-mini-avatar {
          width: 24px;
          height: 24px;
          border-radius: 50%;
        }

        .creator-mini-name {
          color: white;
          font-weight: 600;
          font-size: 13px;
        }

        /* Tickets & Actions */
        .details-col-tickets {
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .tickets-status-card {
          background: rgba(220, 38, 38, 0.05);
          border: 1px solid rgba(220, 38, 38, 0.2);
          border-radius: 12px;
          padding: 20px;
          text-align: center;
        }

        .availability-summary {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          font-size: 14px;
          font-weight: 700;
          color: white;
          margin-bottom: 16px;
        }

        .availability-summary iconify-icon {
          color: var(--color-primary);
        }

        .mini-ticket-scroller {
          flex: 1;
          display: flex;
          flex-direction: column;
          gap: 8px;
          overflow-y: auto;
          padding-right: 4px;
        }

        .mini-ticket-card {
          background: rgba(255,255,255,0.03);
          border: 1px solid var(--color-card-border);
          border-radius: 10px;
          padding: 12px 16px;
        }

        .mini-ticket-info {
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .mini-ticket-type {
          font-size: 12px;
          font-weight: 700;
          color: rgba(255,255,255,0.6);
        }

        .mini-ticket-price {
          font-size: 16px;
          font-weight: 800;
          color: white;
        }

        .status-placeholder-msg, .past-event-msg {
          font-weight: 700;
          color: rgba(255,255,255,0.4);
          padding: 8px;
        }

        /* Responsive Mobile Fallback */
        @media (max-width: 1024px) {
          .event-detail-layout {
            overflow-y: auto;
            padding: 0 20px 20px;
          }
          .details-row {
            grid-template-columns: 1fr;
          }
          .venue-host-split {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  )
}
