import { useState, useCallback } from 'react'
import { useParams, Link, useNavigate } from 'react-router-dom'
import { useQuery } from 'convex/react'
import { api } from '../../convex/_generated/api'
import { Id } from '../../convex/_generated/dataModel'
import { useScrollAnimation } from '../hooks/useScrollAnimation'
import { QueueSection, CheckoutModal } from '../components/events'
import { CalendarExportModal } from '../components/CalendarExportModal'
import {
  formatEventTime,
  formatEventDate,
  formatPrice,
  getSaleStatusBadge,
  getAvailabilityText,
  isEventPast,
} from '../utils/eventFormatters'

export function EventDetail() {
  const { eventId } = useParams<{ eventId: string }>()
  const navigate = useNavigate()
  const animate = useScrollAnimation()
  const [isCheckoutOpen, setIsCheckoutOpen] = useState(false)
  const [isCalendarExportOpen, setIsCalendarExportOpen] = useState(false)

  const handleAdmitted = useCallback(() => {
    setIsCheckoutOpen(true)
  }, [])

  // Note: api.events will be available once convex dev is run
  // @ts-expect-error - events module will be generated by convex
  const eventDetail = useQuery(
    api.events?.getEventDetail || 'skip',
    eventId ? { eventId: eventId as Id<'events'> } : 'skip'
  )

  // @ts-expect-error - events module will be generated by convex
  const relatedEvents = useQuery(
    api.events?.getEvents || 'skip',
    eventDetail?.event.city
      ? {
          page: 0,
          pageSize: 4,
          city: eventDetail.event.city,
          saleStatus: 'on_sale' as const,
        }
      : 'skip'
  )

  if (!eventDetail) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin h-12 w-12 border-4 border-cyan-500 border-t-transparent rounded-full"></div>
      </div>
    )
  }

  const { event, creator, ticketTypes, userContext } = eventDetail
  const statusBadge = getSaleStatusBadge(event.saleStatus)
  const isPast = isEventPast(event.endAtUtc)
  const hasTickets = ticketTypes.length > 0

  const handleCheckoutSuccess = (orderId: string) => {
    setIsCheckoutOpen(false)
    navigate(`/events/confirmation?orderId=${orderId}`)
  }

  const handleRequeue = () => {
    setIsCheckoutOpen(false)
    // QueueSection will handle re-joining if we clear any local state if needed
  }

  return (
    <div className="event-detail-layout">
      {/* Navigation Header */}
      <div className="detail-nav-header">
        <button 
          onClick={() => navigate('/events')}
          className="back-btn"
        >
          <iconify-icon icon="solar:arrow-left-bold"></iconify-icon>
          <span>Back to Events</span>
        </button>
      </div>

      {/* Hero Section */}
      <div ref={animate} data-animate className="event-hero">
        <div className="hero-image-container">
          <img
            src={event.imageUrl}
            alt={event.title}
            className="hero-image"
          />
          <div className="hero-overlay"></div>
        </div>

        <div className="hero-content">
          <div className="flex items-start gap-4 mb-4">
            <h1 className="hero-title">{event.title}</h1>
            <div className={`${statusBadge.bgColor} ${statusBadge.color} px-3 py-1 rounded-full text-sm font-bold`}>
              {statusBadge.text}
            </div>
          </div>

          <div className="hero-meta">
            <div className="meta-item">
              <iconify-icon icon="solar:calendar-bold" class="meta-icon"></iconify-icon>
              <span>{formatEventTime(event.startAtUtc, event.timezone)}</span>
            </div>
            <div className="meta-item">
              <iconify-icon icon="solar:map-point-bold" class="meta-icon"></iconify-icon>
              <span>{event.city}</span>
            </div>
            <div className="meta-item">
              <iconify-icon icon="solar:users-group-two-rounded-bold" class="meta-icon"></iconify-icon>
              <span>{getAvailabilityText(event.capacity, event.ticketsSold)}</span>
            </div>
          </div>

          {!isPast && (
            <button
              onClick={() => setIsCalendarExportOpen(true)}
              className="export-calendar-button"
            >
              <iconify-icon icon="solar:calendar-add-bold"></iconify-icon>
              <span>Add to Calendar</span>
            </button>
          )}
        </div>
      </div>

      {/* Main Content */}
      <div className="event-content-grid">
        {/* Left Column - Event Info */}
        <div className="event-main">
          {/* Description */}
          <section className="content-section">
            <h2 className="section-title">About This Event</h2>
            <p className="section-text">{event.description}</p>
          </section>

          {/* Venue Info */}
          <section className="content-section">
            <h2 className="section-title">Venue</h2>
            <div className="venue-info">
              <div className="flex items-start gap-3">
                <iconify-icon icon="solar:map-point-bold" class="text-cyan-400 text-2xl mt-1"></iconify-icon>
                <div>
                  <p className="text-white font-bold mb-1">{event.address}</p>
                  <p className="text-gray-400 text-sm">{event.city}</p>
                  <p className="text-gray-500 text-xs mt-1">Timezone: {event.timezone}</p>
                </div>
              </div>
            </div>
          </section>

          {/* Ticket Types */}
          {hasTickets && (
            <section className="content-section">
              <h2 className="section-title">Ticket Types</h2>
              <div className="ticket-types-grid">
                {ticketTypes.map((ticket: typeof ticketTypes[number]) => (
                  <div key={ticket._id} className="ticket-type-card">
                    <div className="flex items-start justify-between mb-2">
                      <div>
                        <h3 className="ticket-type-name">{ticket.type.replace('_', ' ').toUpperCase()}</h3>
                        {ticket.description && (
                          <p className="ticket-type-desc">{ticket.description}</p>
                        )}
                      </div>
                      <span className="ticket-type-price">{formatPrice(ticket.price)}</span>
                    </div>
                    <div className="ticket-type-availability">
                      <span className="text-xs text-gray-400">
                        {ticket.availableQuantity} of {ticket.quantity} available
                      </span>
                      <div className="availability-bar">
                        <div
                          className="availability-bar-fill"
                          style={{
                            width: `${(ticket.quantitySold / ticket.quantity) * 100}%`,
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Creator Info */}
          <section className="content-section">
            <h2 className="section-title">Hosted By</h2>
            <Link to={`/profile/${creator._id}`} className="creator-card">
              <img src={creator.avatar} alt={creator.displayName} className="creator-avatar" />
              <div>
                <p className="creator-name">{creator.displayName}</p>
                <p className="creator-username">@{creator.username}</p>
              </div>
            </Link>
          </section>
        </div>

        {/* Right Column - Actions & Related */}
        <div className="event-sidebar">
          {/* Action Card */}
          <div className="action-card-container">
            {isPast ? (
              <div className="action-card text-center py-8">
                <p className="text-gray-400 text-sm mb-2">This event has ended</p>
              </div>
            ) : event.saleStatus === 'on_sale' ? (
              <QueueSection 
                eventId={event._id} 
                onAdmitted={handleAdmitted} 
              />
            ) : event.saleStatus === 'upcoming' ? (
              <div className="action-card text-center py-8">
                <p className="text-yellow-400 font-bold mb-2">Coming Soon</p>
                <p className="text-gray-400 text-sm">Tickets not yet available</p>
              </div>
            ) : event.saleStatus === 'sold_out' ? (
              <div className="action-card text-center py-8">
                <p className="text-red-400 font-bold mb-2">Sold Out</p>
                <p className="text-gray-400 text-sm">This event has sold out</p>
              </div>
            ) : null}
          </div>

          {/* Checkout Modal */}
          {userContext?.checkoutSession && (
            <CheckoutModal
              isOpen={isCheckoutOpen}
              onClose={() => setIsCheckoutOpen(false)}
              eventId={event._id}
              eventTitle={event.title}
              ticketTypes={ticketTypes}
              checkoutSessionId={userContext.checkoutSession._id}
              onSuccess={handleCheckoutSuccess}
              onRequeue={handleRequeue}
            />
          )}

          {/* Calendar Export Modal */}
          <CalendarExportModal
            isOpen={isCalendarExportOpen}
            onClose={() => setIsCalendarExportOpen(false)}
            event={event}
          />

          {/* Related Events */}
          {relatedEvents && relatedEvents.items.length > 0 && (
            <div className="related-events">
              <h3 className="related-title">More Events in {event.city}</h3>
              <div className="related-list">
                {relatedEvents.items
                  .filter((e: typeof relatedEvents.items[number]) => e._id !== event._id)
                  .slice(0, 3)
                  .map((relatedEvent: typeof relatedEvents.items[number]) => (
                    <Link
                      key={relatedEvent._id}
                      to={`/events/${relatedEvent._id}`}
                      className="related-event-card"
                    >
                      <img
                        src={relatedEvent.imageUrl}
                        alt={relatedEvent.title}
                        className="related-event-image"
                      />
                      <div className="related-event-info">
                        <h4 className="related-event-title">{relatedEvent.title}</h4>
                        <p className="related-event-date">
                          {formatEventDate(relatedEvent.startAtUtc, event.timezone)}
                        </p>
                      </div>
                    </Link>
                  ))}
              </div>
            </div>
          )}
        </div>
      </div>

      <style>{`
        .event-detail-layout {
          max-width: 1400px;
          margin: 0 auto;
          padding: 0 20px 40px;
          height: 100%;
          overflow-y: auto;
          scrollbar-width: thin;
          scrollbar-color: var(--color-primary) transparent;
        }

        .event-detail-layout::-webkit-scrollbar {
          width: 6px;
        }

        .event-detail-layout::-webkit-scrollbar-thumb {
          background: var(--color-primary);
          border-radius: 3px;
        }

        .detail-nav-header {
          padding: 20px 0;
          display: flex;
          align-items: center;
        }

        .back-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--color-card-border);
          border-radius: 8px;
          padding: 10px 16px;
          color: white;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s;
        }

        .back-btn:hover {
          background: rgba(255, 255, 255, 0.1);
          transform: translateX(-4px);
        }

        .event-hero {
          position: relative;
          margin-bottom: 40px;
          border-radius: 16px;
          overflow: hidden;
        }

        .hero-image-container {
          position: relative;
          height: 400px;
          overflow: hidden;
        }

        .hero-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .hero-overlay {
          position: absolute;
          inset: 0;
          background: linear-gradient(to top, rgba(0, 0, 0, 0.9), transparent);
        }

        .hero-content {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          padding: 40px;
        }

        .hero-title {
          font-size: 36px;
          font-weight: 800;
          color: white;
          margin: 0;
          line-height: 1.2;
        }

        .hero-meta {
          display: flex;
          flex-wrap: wrap;
          gap: 24px;
          margin-top: 16px;
        }

        .meta-item {
          display: flex;
          align-items: center;
          gap: 8px;
          color: white;
          font-size: 14px;
        }

        .meta-icon {
          color: var(--color-primary);
          font-size: 20px;
        }

        .export-calendar-button {
          margin-top: 16px;
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 12px 24px;
          background: rgba(6, 182, 212, 0.2);
          border: 1px solid var(--color-primary);
          border-radius: 8px;
          color: var(--color-primary);
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s;
        }

        .export-calendar-button:hover {
          background: rgba(6, 182, 212, 0.3);
          transform: translateY(-2px);
        }

        .export-calendar-button iconify-icon {
          font-size: 20px;
        }

        .event-content-grid {
          display: grid;
          grid-template-columns: 1fr 400px;
          gap: 40px;
        }

        .event-main {
          display: flex;
          flex-direction: column;
          gap: 32px;
        }

        .content-section {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--color-card-border);
          border-radius: 12px;
          padding: 24px;
        }

        .section-title {
          font-size: 20px;
          font-weight: 700;
          color: white;
          margin: 0 0 16px 0;
        }

        .section-text {
          color: var(--color-text-dim);
          line-height: 1.6;
          margin: 0;
        }

        .venue-info {
          color: white;
        }

        .ticket-types-grid {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .ticket-type-card {
          background: rgba(0, 0, 0, 0.3);
          border: 1px solid var(--color-card-border);
          border-radius: 8px;
          padding: 16px;
        }

        .ticket-type-name {
          font-size: 14px;
          font-weight: 700;
          color: var(--color-primary);
          margin: 0 0 4px 0;
        }

        .ticket-type-desc {
          font-size: 12px;
          color: var(--color-text-dim);
          margin: 0;
        }

        .ticket-type-price {
          font-size: 20px;
          font-weight: 700;
          color: white;
        }

        .ticket-type-availability {
          margin-top: 12px;
        }

        .availability-bar {
          height: 4px;
          background: rgba(255, 255, 255, 0.1);
          border-radius: 2px;
          margin-top: 4px;
          overflow: hidden;
        }

        .availability-bar-fill {
          height: 100%;
          background: var(--color-primary);
          transition: width 0.3s ease;
        }

        .creator-card {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 16px;
          background: rgba(0, 0, 0, 0.3);
          border: 1px solid var(--color-card-border);
          border-radius: 8px;
          text-decoration: none;
          transition: all 0.2s;
        }

        .creator-card:hover {
          border-color: var(--color-primary);
          transform: translateY(-2px);
        }

        .creator-avatar {
          width: 48px;
          height: 48px;
          border-radius: 50%;
          object-fit: cover;
        }

        .creator-name {
          font-size: 14px;
          font-weight: 700;
          color: white;
          margin: 0;
        }

        .creator-username {
          font-size: 12px;
          color: var(--color-primary);
          margin: 4px 0 0 0;
        }

        .event-sidebar {
          display: flex;
          flex-direction: column;
          gap: 24px;
        }

        .related-events {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--color-card-border);
          border-radius: 12px;
          padding: 24px;
        }

        .related-title {
          font-size: 16px;
          font-weight: 700;
          color: white;
          margin: 0 0 16px 0;
        }

        .related-list {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .related-event-card {
          display: flex;
          gap: 12px;
          padding: 12px;
          background: rgba(0, 0, 0, 0.3);
          border: 1px solid var(--color-card-border);
          border-radius: 8px;
          text-decoration: none;
          transition: all 0.2s;
        }

        .related-event-card:hover {
          border-color: var(--color-primary);
          transform: translateY(-2px);
        }

        .related-event-image {
          width: 80px;
          height: 60px;
          object-fit: cover;
          border-radius: 4px;
        }

        .related-event-info {
          flex: 1;
        }

        .related-event-title {
          font-size: 14px;
          font-weight: 600;
          color: white;
          margin: 0 0 4px 0;
          line-height: 1.3;
        }

        .related-event-date {
          font-size: 12px;
          color: var(--color-text-dim);
          margin: 0;
        }

        @media (max-width: 1024px) {
          .event-content-grid {
            grid-template-columns: 1fr;
          }
          
          .action-card {
            position: static;
          }
        }

        @media (max-width: 768px) {
          .hero-image-container {
            height: 300px;
          }
          
          .hero-content {
            padding: 24px;
          }
          
          .hero-title {
            font-size: 24px;
          }
          
          .hero-meta {
            flex-direction: column;
            gap: 12px;
          }
        }
      `}</style>
    </div>
  )
}
